import localFont from "next/font/local";
import "./globals.css";
import { getData } from "@/lib/data";
import Header from "@/components/Header";
import Banner from "@/components/Banner";


export const metadata = {
  title: "Recipe web App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
 const allData =  getData()
 console.log(allData);
 
  return (
    <html lang="en">
      <body
        // className={inter.className}
      >
        <div>
          <Header />
          <Banner />
        {children}
        </div>
      </body>
    </html>
  );
}
